version: '3'

services:
  mysql:
    build: .
    image: iwashita511/mysql-image
    container_name: mysql-container
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: graphql-database
      MYSQL_USER: user001
      MYSQL_PASSWORD: user001#
    tty: true